/**
 * Pure generator for src/app/fonts.generated.ts — the next/font module
 * layout.tsx imports. next/font requires literal, module-scope loader calls,
 * so fonts can only change live by regenerating this file (never a runtime
 * <link>: CSP font-src 'self', self-hosting and no-CLS all depend on it).
 *
 * Roles (in this order): heading, body, accent, mono. A family used by more
 * than one role is loaded ONCE (union of weights / italic) on the first role's
 * variable; later roles alias it via <html style> (today: body → heading).
 * Unknown families fall back to the role default with a warning.
 *
 * Two header kinds (PF5). generateFontsModule() with NO design emits the
 * DEFAULT kind: the template's default fonts (today's live fonts), seeded on
 * rollout and never held to design.json parity. generateFontsModule(typography)
 * emits the SYNCED kind: generated from design.json, which the --check drift
 * step and the parity test enforce. fontsModuleKind(source) tells them apart.
 *
 * BYTE PARITY: the platform (onboarding lib/content/font-module-generator.ts)
 * ports this function; golden fixtures in src/lib/theme/__fixtures__/fonts/
 * are copied there. Change both together.
 */
import { DEFAULT_TYPOGRAPHY, FONT_MANIFEST, MONO_FAMILY, type FontManifestEntry } from './font-manifest'

export type FontRole = 'heading' | 'body' | 'accent' | 'mono'
// pinnedFonts: families a Design Studio lock still references (the platform's
// lib/design/lock-pins.ts). Each gets a --font-pin-<slug> variable: an alias
// when a role already loads the family, otherwise its own load. Absent/empty →
// the output is unchanged.
export type FontTypographyInput = { headingFont?: string; bodyFont?: string; accentFont?: string; pinnedFonts?: readonly string[] }

export function fontPinVariable(family: string): string {
  return `--font-pin-${family.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')}`
}

type RoleSpec = { role: FontRole; variable: string; weights: readonly string[]; italic: boolean }
export const ROLE_SPECS: readonly RoleSpec[] = [
  { role: 'heading', variable: '--font-heading-loaded', weights: ['400', '500', '700'], italic: false },
  { role: 'body', variable: '--font-body-loaded', weights: ['400', '500', '700'], italic: false },
  { role: 'accent', variable: '--font-accent-loaded', weights: ['400', '500'], italic: true },
  { role: 'mono', variable: '--font-mono-loaded', weights: ['400', '500'], italic: false },
]

export type FontsModuleKind = 'default' | 'synced'

export const FONTS_MODULE_HEADERS: Readonly<Record<FontsModuleKind, readonly string[]>> = {
  default: [
    '// This file is generated by scripts/generate-fonts.ts — default — not synced from design.json.',
    '// It loads the template default fonts; run `npm run generate-fonts` to sync it to content/design.json (typography).',
    '// The Revaltus platform rewrites it when the site fonts change (Design Studio / Theme Studio).',
  ],
  synced: [
    '// This file is generated by scripts/generate-fonts.ts from content/design.json.',
    '// Edit design.json (typography) and run `npm run generate-fonts` instead of editing it.',
    '// The Revaltus platform rewrites it when the site fonts change (Design Studio / Theme Studio).',
  ],
}

// generateAllFontsModule only (CI `fonts` job, never committed) — neither kind.
const ALL_FONTS_HEADER_LINES = [
  '// This file is generated by scripts/generate-fonts.ts --all for the CI `fonts` job.',
  '// It loads every manifest font once. Never commit it.',
]

/**
 * Which kind of generated module `source` is, by its first line; null if neither.
 * A trailing \r is ignored so a CRLF checkout (git autocrlf) still classifies.
 */
export function fontsModuleKind(source: string): FontsModuleKind | null {
  const first = source.split('\n', 1)[0].replace(/\r$/, '')
  if (first === FONTS_MODULE_HEADERS.default[0]) return 'default'
  if (first === FONTS_MODULE_HEADERS.synced[0]) return 'synced'
  return null
}

type Load = { entry: FontManifestEntry; variable: string; weights: Set<string>; italic: boolean }

const entryFor = (family: string | undefined): FontManifestEntry | undefined =>
  FONT_MANIFEST.find((e) => e.family === family)

function resolveFamilies(t: FontTypographyInput): { families: Record<FontRole, FontManifestEntry>; warnings: string[] } {
  const warnings: string[] = []
  const pick = (role: FontRole, wanted: string | undefined, fallback: string): FontManifestEntry => {
    const found = entryFor(wanted)
    if (found) return found
    if (wanted) warnings.push(`Unknown ${role} font "${wanted}" — using ${fallback}.`)
    return entryFor(fallback) as FontManifestEntry
  }
  return {
    families: {
      heading: pick('heading', t.headingFont, DEFAULT_TYPOGRAPHY.headingFont),
      body: pick('body', t.bodyFont, DEFAULT_TYPOGRAPHY.bodyFont),
      accent: pick('accent', t.accentFont, DEFAULT_TYPOGRAPHY.accentFont),
      mono: entryFor(MONO_FAMILY) as FontManifestEntry,
    },
    warnings,
  }
}

const byWeight = (a: string, b: string): number => Number(a) - Number(b)

function renderCall(name: string, load: Load): string {
  const weights = [...load.weights].sort(byWeight)
  return [
    `const ${name} = ${load.entry.importName}({`,
    `  subsets: ['latin'],`,
    `  weight: [${weights.map((w) => `'${w}'`).join(', ')}],`,
    ...(load.italic ? [`  style: ['normal', 'italic'],`] : []),
    `  variable: '${load.variable}',`,
    `  display: 'swap',`,
    `})`,
  ].join('\n')
}

function renderModule(header: readonly string[], loads: Load[], aliases: [string, string][]): string {
  const variables = loads.map((_, i) => `\${font${i}.variable}`).join(' ')
  const aliasDecl =
    aliases.length === 0
      ? 'export const fontAliases: CSSProperties = {}'
      : [
          'export const fontAliases: CSSProperties = {',
          ...aliases.map(([v, target]) => `  '${v}': 'var(${target})',`),
          '} as CSSProperties',
        ].join('\n')
  return [
    ...header,
    '',
    "import type { CSSProperties } from 'react'",
    `import { ${loads.map((l) => l.entry.importName).join(', ')} } from 'next/font/google'`,
    '',
    loads.map((l, i) => renderCall(`font${i}`, l)).join('\n\n'),
    '',
    '/** next/font variable classes for <html className>. */',
    `export const fontVariables = \`${variables}\``,
    '',
    '/** Roles sharing a family point at the loaded variable (applied as <html style>). */',
    aliasDecl,
    '',
  ].join('\n')
}

/**
 * No argument → the DEFAULT kind (template default fonts). A typography object
 * (even `{}`, e.g. a design.json without typography) → the SYNCED kind.
 */
export function generateFontsModule(t?: FontTypographyInput): { source: string; warnings: string[] } {
  const { families, warnings } = resolveFamilies(t ?? {})
  const loads: Load[] = []
  const aliases: [string, string][] = []
  for (const spec of ROLE_SPECS) {
    const entry = families[spec.role]
    const supported = spec.weights.filter((w) => entry.weights.includes(w))
    const existing = loads.find((l) => l.entry.family === entry.family)
    if (existing) {
      for (const w of supported) existing.weights.add(w)
      existing.italic = existing.italic || (spec.italic && entry.italic)
      aliases.push([spec.variable, existing.variable])
      continue
    }
    loads.push({
      entry,
      variable: spec.variable,
      weights: new Set(supported.length > 0 ? supported : [entry.weights[0]]),
      italic: spec.italic && entry.italic,
    })
  }
  for (const family of [...new Set(t?.pinnedFonts ?? [])].sort()) {
    const entry = entryFor(family)
    if (!entry) {
      warnings.push(`Unknown pinned font "${family}" — skipped.`)
      continue
    }
    const variable = fontPinVariable(family)
    // A pin may stand in for any role, so its family loads every role weight.
    const weights = ROLE_SPECS[0].weights.filter((w) => entry.weights.includes(w))
    const existing = loads.find((l) => l.entry.family === entry.family)
    if (existing) {
      for (const w of weights) existing.weights.add(w)
      existing.italic = existing.italic || entry.italic
      aliases.push([variable, existing.variable])
      continue
    }
    loads.push({ entry, variable, weights: new Set(weights.length > 0 ? weights : [entry.weights[0]]), italic: entry.italic })
  }
  return { source: renderModule(FONTS_MODULE_HEADERS[t === undefined ? 'default' : 'synced'], loads, aliases), warnings }
}

// CI only (the `fonts` job): every manifest family once, all its weights, so a
// `next build` proves each family resolves. Never committed.
export function generateAllFontsModule(): string {
  const loads: Load[] = FONT_MANIFEST.map((entry, i) => ({
    entry,
    variable: `--font-ci-${i}`,
    weights: new Set(entry.weights),
    italic: entry.italic,
  }))
  return renderModule(ALL_FONTS_HEADER_LINES, loads, [])
}
