import { describe, expect, it } from 'vitest'
import { FONT_MANIFEST } from './font-manifest'
import { FONTS_MODULE_HEADERS, fontsModuleKind, generateAllFontsModule, generateFontsModule } from './font-module'

// PF5: two header kinds. DEFAULT = the template's default fonts (today's live
// fonts), seeded on rollout and never checked against design.json. SYNCED =
// generated from a design.json typography (script / Studio / Controls write),
// which CI + vitest hold to design.json parity.
const DEFAULT_HEADER = [
  '// This file is generated by scripts/generate-fonts.ts — default — not synced from design.json.',
  '// It loads the template default fonts; run `npm run generate-fonts` to sync it to content/design.json (typography).',
  '// The Revaltus platform rewrites it when the site fonts change (Design Studio / Theme Studio).',
]
const SYNCED_HEADER = [
  '// This file is generated by scripts/generate-fonts.ts from content/design.json.',
  '// Edit design.json (typography) and run `npm run generate-fonts` instead of editing it.',
  '// The Revaltus platform rewrites it when the site fonts change (Design Studio / Theme Studio).',
]

// Today's layout.tsx fonts (R1), below the header.
const DEFAULT_BODY = [
  '',
  "import type { CSSProperties } from 'react'",
  "import { Public_Sans, Fraunces, Geist_Mono } from 'next/font/google'",
  '',
  'const font0 = Public_Sans({',
  "  subsets: ['latin'],",
  "  weight: ['400', '500', '700'],",
  "  variable: '--font-heading-loaded',",
  "  display: 'swap',",
  '})',
  '',
  'const font1 = Fraunces({',
  "  subsets: ['latin'],",
  "  weight: ['400', '500'],",
  "  style: ['normal', 'italic'],",
  "  variable: '--font-accent-loaded',",
  "  display: 'swap',",
  '})',
  '',
  'const font2 = Geist_Mono({',
  "  subsets: ['latin'],",
  "  weight: ['400', '500'],",
  "  variable: '--font-mono-loaded',",
  "  display: 'swap',",
  '})',
  '',
  '/** next/font variable classes for <html className>. */',
  'export const fontVariables = `${font0.variable} ${font1.variable} ${font2.variable}`',
  '',
  '/** Roles sharing a family point at the loaded variable (applied as <html style>). */',
  'export const fontAliases: CSSProperties = {',
  "  '--font-body-loaded': 'var(--font-heading-loaded)',",
  '} as CSSProperties',
  '',
]
const DEFAULT_MODULE = [...DEFAULT_HEADER, ...DEFAULT_BODY].join('\n')
const SYNCED_DEFAULT_TYPOGRAPHY_MODULE = [...SYNCED_HEADER, ...DEFAULT_BODY].join('\n')

describe('generateFontsModule', () => {
  it('with no design emits the DEFAULT kind: today’s layout.tsx fonts (R1, PF5)', () => {
    expect(generateFontsModule()).toEqual({ source: DEFAULT_MODULE, warnings: [] })
    expect(fontsModuleKind(DEFAULT_MODULE)).toBe('default')
  })

  it('from a design.json typography emits the SYNCED kind; default typography = same fonts', () => {
    expect(generateFontsModule({ headingFont: 'Public Sans', bodyFont: 'Public Sans' })).toEqual({
      source: SYNCED_DEFAULT_TYPOGRAPHY_MODULE,
      warnings: [],
    })
    // accentFont absent (pre-Ink & Clay design.json) = Fraunces, silently.
    expect(generateFontsModule({}).source).toBe(SYNCED_DEFAULT_TYPOGRAPHY_MODULE)
    expect(generateFontsModule({ headingFont: 'Public Sans', bodyFont: 'Public Sans', accentFont: 'Fraunces' }).source).toBe(
      SYNCED_DEFAULT_TYPOGRAPHY_MODULE,
    )
    expect(fontsModuleKind(SYNCED_DEFAULT_TYPOGRAPHY_MODULE)).toBe('synced')
  })

  it('exposes both headers, which differ from the first line on', () => {
    expect(FONTS_MODULE_HEADERS).toEqual({ default: DEFAULT_HEADER, synced: SYNCED_HEADER })
    expect(DEFAULT_HEADER[0]).toContain('default — not synced from design.json')
    expect(DEFAULT_HEADER[0]).not.toBe(SYNCED_HEADER[0])
  })

  it('loads a shared family once, unions weights/italic and aliases the later role', () => {
    const { source } = generateFontsModule({ headingFont: 'Fraunces', bodyFont: 'Inter', accentFont: 'Fraunces' })
    expect(source).toContain("import { Fraunces, Inter, Geist_Mono } from 'next/font/google'")
    expect(source).toContain(
      "const font0 = Fraunces({\n  subsets: ['latin'],\n  weight: ['400', '500', '700'],\n  style: ['normal', 'italic'],\n  variable: '--font-heading-loaded',",
    )
    expect(source).toContain("variable: '--font-body-loaded'")
    expect(source).toContain("  '--font-accent-loaded': 'var(--font-heading-loaded)',")
    expect(source).not.toContain("'--font-body-loaded': 'var(")
  })

  it('drops italic for families without one and clamps weights to what ships', () => {
    const { source } = generateFontsModule({ headingFont: 'Manrope', bodyFont: 'DM Serif Display', accentFont: 'Manrope' })
    expect(source).not.toContain('italic')
    expect(source).toContain("const font1 = DM_Serif_Display({\n  subsets: ['latin'],\n  weight: ['400'],")
  })

  it('emits an empty alias map when every role has its own family', () => {
    const { source } = generateFontsModule({ headingFont: 'Lora', bodyFont: 'Inter', accentFont: 'Fraunces' })
    expect(source).toContain('export const fontAliases: CSSProperties = {}\n')
  })

  it('falls back per role on an unknown family, with a warning (never breaks a build)', () => {
    const r = generateFontsModule({ headingFont: 'Comic Neue', bodyFont: 'Inter', accentFont: 'Nope' })
    expect(r.warnings).toEqual(['Unknown heading font "Comic Neue" — using Public Sans.', 'Unknown accent font "Nope" — using Fraunces.'])
    expect(r.source).toContain("import { Public_Sans, Inter, Fraunces, Geist_Mono } from 'next/font/google'")
    expect(fontsModuleKind(r.source)).toBe('synced')
  })

  it('is deterministic', () => {
    const t = { headingFont: 'Source Serif 4', bodyFont: 'Source Sans 3', accentFont: 'Playfair Display' }
    expect(generateFontsModule(t).source).toBe(generateFontsModule({ ...t }).source)
    expect(generateFontsModule().source).toBe(generateFontsModule().source)
  })
})

describe('fontsModuleKind', () => {
  it('returns null for anything that is not a generated default/synced module', () => {
    expect(fontsModuleKind('')).toBeNull()
    expect(fontsModuleKind("import { Inter } from 'next/font/google'\n")).toBeNull()
    expect(fontsModuleKind(generateAllFontsModule())).toBeNull()
    // A header line must match whole, not as a prefix of something else.
    expect(fontsModuleKind(`${SYNCED_HEADER[0]} (edited)\n`)).toBeNull()
  })

  it('tolerates CRLF line endings (a Windows checkout with autocrlf)', () => {
    const crlf = (s: string) => s.replace(/\n/g, '\r\n')
    expect(fontsModuleKind(crlf(generateFontsModule().source))).toBe('default')
    expect(fontsModuleKind(crlf(generateFontsModule({}).source))).toBe('synced')
    expect(fontsModuleKind(`${SYNCED_HEADER[0]}\r`)).toBe('synced')
  })
})

describe('generateAllFontsModule', () => {
  it('loads every manifest family exactly once with all of its weights', () => {
    const source = generateAllFontsModule()
    for (const [i, e] of FONT_MANIFEST.entries()) {
      expect(source).toContain(`const font${i} = ${e.importName}({`)
      expect(source).toContain(`variable: '--font-ci-${i}'`)
    }
    expect(source.match(/ = [A-Za-z0-9_]+\(\{/g)).toHaveLength(FONT_MANIFEST.length)
    expect(source).toContain('export const fontAliases: CSSProperties = {}')
  })
})
