// This file is generated by scripts/generate-fonts.ts — default — not synced from design.json.
// It loads the template default fonts; run `npm run generate-fonts` to sync it to content/design.json (typography).
// The Revaltus platform rewrites it when the site fonts change (Design Studio / Theme Studio).

import type { CSSProperties } from 'react'
import { Public_Sans, Fraunces, Geist_Mono } from 'next/font/google'

const font0 = Public_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-heading-loaded',
  display: 'swap',
})

const font1 = Fraunces({
  subsets: ['latin'],
  weight: ['400', '500'],
  style: ['normal', 'italic'],
  variable: '--font-accent-loaded',
  display: 'swap',
})

const font2 = Geist_Mono({
  subsets: ['latin'],
  weight: ['400', '500'],
  variable: '--font-mono-loaded',
  display: 'swap',
})

/** next/font variable classes for <html className>. */
export const fontVariables = `${font0.variable} ${font1.variable} ${font2.variable}`

/** Roles sharing a family point at the loaded variable (applied as <html style>). */
export const fontAliases: CSSProperties = {
  '--font-body-loaded': 'var(--font-heading-loaded)',
} as CSSProperties
